package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSkillPrintsGeneratedSkill(t *testing.T) {
	_, c := newFakeClickUp(t)
	out, code := runCLI(t, c, "skill")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0\noutput:\n%s", code, out)
	}
	for _, want := range []string{
		"name: clickup-axi",
		"<!-- Generated by `clickup-axi skill --write` from skill_template.md",
		"clickup-axi                                                              # who am I + workspaces (auth check)",
		"clickup-axi tasks <id> --full                                            # complete description and all fetched comments",
		`clickup-axi search "<query>" --assignee all --space "<space>"            # widen beyond your tasks`,
		"clickup-axi spaces",
		`clickup-axi lists --space "<space>"`,
		`clickup-axi lists --space "<space>" --archived`,
		`clickup-axi tasks edit <id> --status "<status>"`,
		`clickup-axi tasks edit <id> --priority <p> --due <date> --name "<title>" # priority: urgent|high|normal|low|none; due: YYYY-MM-DD or none; fields combine in one call`,
		`clickup-axi tasks edit <id> --append-body "<markdown>" --add-tag <tag>   # --body replaces the description, --append-body adds below it; tags must already exist in the space`,
		`clickup-axi tasks edit <id> --parent <task id>`,
		"## Behavior contract",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("generated skill missing %q\noutput:\n%s", want, out)
		}
	}
	if strings.Contains(out, "{{COMMANDS}}") {
		t.Errorf("template placeholder was not replaced\noutput:\n%s", out)
	}
	if strings.Contains(out, "\nclickup-axi skill") {
		t.Errorf("maintainer-only skill command leaked into the agent skill\noutput:\n%s", out)
	}
}

// TestCommittedSkillIsFresh is the local drift guard: plain `go test`
// fails when skills/clickup-axi/SKILL.md no longer matches the
// generator, mirroring `clickup-axi skill --check` in CI. The test
// runs in internal/cli, so it reaches the committed file through the
// repository root.
func TestCommittedSkillIsFresh(t *testing.T) {
	committed := filepath.Join("..", "..", skillPath)
	got, err := os.ReadFile(committed)
	if err != nil {
		t.Fatalf("read %s: %v", committed, err)
	}
	if string(got) != GenerateSkill() {
		t.Errorf("%s is stale - run `go run ./cmd/clickup-axi skill --write` and commit the result", skillPath)
	}
}

func TestSkillCheckAndWriteLifecycle(t *testing.T) {
	_, c := newFakeClickUp(t)
	t.Chdir(t.TempDir())
	if err := os.MkdirAll("skills/clickup-axi", 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(skillPath, []byte("stale content"), 0o644); err != nil {
		t.Fatal(err)
	}

	out, code := runCLI(t, c, "skill", "--check")
	if code != 1 {
		t.Fatalf("stale --check exit code = %d, want 1\noutput:\n%s", code, out)
	}
	if !strings.Contains(out, "error: "+skillPath+" is stale") ||
		!strings.Contains(out, "Run `clickup-axi skill --write`") {
		t.Errorf("stale --check must name the file and point at --write\noutput:\n%s", out)
	}

	out, code = runCLI(t, c, "skill", "--write")
	if code != 0 || !strings.Contains(out, "skill: wrote "+skillPath) {
		t.Fatalf("--write failed: exit %d\noutput:\n%s", code, out)
	}

	out, code = runCLI(t, c, "skill", "--check")
	if code != 0 || !strings.Contains(out, "skill: "+skillPath+" is up to date") {
		t.Errorf("fresh --check: exit %d\noutput:\n%s", code, out)
	}

	out, code = runCLI(t, c, "skill", "--write")
	if code != 0 || !strings.Contains(out, "already up to date (no-op)") {
		t.Errorf("repeated --write must be an exit-0 no-op: exit %d\noutput:\n%s", code, out)
	}
}

func TestSkillOutsideCheckoutFails(t *testing.T) {
	_, c := newFakeClickUp(t)
	t.Chdir(t.TempDir())

	out, code := runCLI(t, c, "skill", "--check")
	if code != 1 || !strings.Contains(out, "run from a clickup-axi checkout") {
		t.Errorf("--check outside a checkout: exit %d\noutput:\n%s", code, out)
	}

	out, code = runCLI(t, c, "skill", "--write")
	if code != 1 || !strings.Contains(out, "run from a clickup-axi checkout") {
		t.Errorf("--write outside a checkout must not create directories: exit %d\noutput:\n%s", code, out)
	}
	if _, err := os.Stat("skills"); !os.IsNotExist(err) {
		t.Errorf("--write outside a checkout created a skills/ tree")
	}
}

func TestSkillUnknownFlagIsUsageError(t *testing.T) {
	_, c := newFakeClickUp(t)
	out, code := runCLI(t, c, "skill", "--frobnicate")
	if code != 2 {
		t.Fatalf("exit code = %d, want 2\noutput:\n%s", code, out)
	}
	if !strings.Contains(out, "valid: --check, --write") {
		t.Errorf("usage error does not list valid flags inline\noutput:\n%s", out)
	}
}

func TestSkillCheckWriteCombinedIsUsageError(t *testing.T) {
	_, c := newFakeClickUp(t)
	out, code := runCLI(t, c, "skill", "--check", "--write")
	if code != 2 {
		t.Fatalf("exit code = %d, want 2\noutput:\n%s", code, out)
	}
	if !strings.Contains(out, "cannot be combined") {
		t.Errorf("combined flags must be rejected explicitly\noutput:\n%s", out)
	}
}
