package hostcfg

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// openCodeMarker identifies a plugin file as ours; a file without it
// is the user's and is never overwritten or removed.
const openCodeMarker = "generated by `clickup-axi setup`"

// pluginJS renders the managed OpenCode plugin. OpenCode has no
// session-start context hook (anomalyco/opencode#15224 is unmerged),
// so the supported shape is a chat.message hook that injects the CLI's
// stdout as a synthetic text part on the first message of a session -
// nothing reaches the model before that, so the effect is the same.
func pluginJS(hookCmd string) string {
	return `// clickup-axi session context plugin
// ` + openCodeMarker + ` - do not edit; rerun ` + "`clickup-axi setup`" + ` to update,
// ` + "`clickup-axi setup --remove`" + ` to uninstall.
export const ClickupContextPlugin = async ({ $ }) => {
  const seen = new Set()
  return {
    "chat.message": async (input, output) => {
      if (seen.has(input.sessionID)) return
      seen.add(input.sessionID)
      let context
      try {
        context = (await $` + "`" + hookCmd + "`" + `.quiet().text()).trim()
      } catch {
        return // CLI missing or failing must never break the session
      }
      if (!context) return
      output.parts.push({
        messageID: output.message.id,
        sessionID: input.sessionID,
        type: "text",
        synthetic: true,
        text: "<clickup-context>\n" + context + "\n</clickup-context>",
      })
    },
  }
}
`
}

func installOpenCode(t Target, hookCmd string) Report {
	want := pluginJS(hookCmd)
	got, err := os.ReadFile(t.Path)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		if err := os.MkdirAll(filepath.Dir(t.Path), 0o755); err != nil {
			return failf(t.Host, t.Path, "could not create %s", filepath.Dir(t.Path))
		}
		if err := os.WriteFile(t.Path, []byte(want), 0o644); err != nil {
			return failf(t.Host, t.Path, "could not write %s", t.Path)
		}
		return Report{Host: t.Host, Path: t.Path, Action: Installed}
	case err != nil:
		return failf(t.Host, t.Path, "could not read %s", t.Path)
	case !strings.Contains(string(got), openCodeMarker):
		return failf(t.Host, t.Path, "existing file is not managed by clickup-axi; move it aside and rerun setup")
	case string(got) == want:
		return Report{Host: t.Host, Path: t.Path, Action: AlreadyInstalled}
	default:
		if err := os.WriteFile(t.Path, []byte(want), 0o644); err != nil {
			return failf(t.Host, t.Path, "could not write %s", t.Path)
		}
		return Report{Host: t.Host, Path: t.Path, Action: Repaired}
	}
}

func removeOpenCode(t Target) Report {
	got, err := os.ReadFile(t.Path)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		return Report{Host: t.Host, Path: t.Path, Action: NotInstalled}
	case err != nil:
		return failf(t.Host, t.Path, "could not read %s", t.Path)
	case !strings.Contains(string(got), openCodeMarker):
		return failf(t.Host, t.Path, "existing file is not managed by clickup-axi; not removing it")
	}
	if err := os.Remove(t.Path); err != nil {
		return failf(t.Host, t.Path, "could not remove %s", t.Path)
	}
	return Report{Host: t.Host, Path: t.Path, Action: Removed}
}
