package hostcfg

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func openCodeTarget(t *testing.T) Target {
	t.Helper()
	return Target{
		Host:      "opencode",
		Path:      filepath.Join(t.TempDir(), "plugins", "clickup-axi.js"),
		Supported: true,
	}
}

func TestInstallOpenCodeWritesManagedPlugin(t *testing.T) {
	tgt := openCodeTarget(t)
	r := installOpenCode(tgt, "clickup-axi context")
	if r.Action != Installed {
		t.Fatalf("action = %v, want Installed (detail %q)", r.Action, r.Detail)
	}
	raw, err := os.ReadFile(tgt.Path)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"generated by `clickup-axi setup`",
		"chat.message",
		`const command = "clickup-axi context"`,
		"$`${{ raw: command }}`",
		"seen.has(input.sessionID)",
		"synthetic: true",
	} {
		if !strings.Contains(string(raw), want) {
			t.Errorf("plugin missing %q\n%s", want, raw)
		}
	}
}

func TestInstallOpenCodeEmbedsHostileCommandSafely(t *testing.T) {
	tgt := openCodeTarget(t)
	hookCmd := "\"/opt/$weird/`ticked`/${brace}/clickup-axi\" context"
	if r := installOpenCode(tgt, hookCmd); r.Action != Installed {
		t.Fatalf("action = %v, want Installed (detail %q)", r.Action, r.Detail)
	}
	raw, err := os.ReadFile(tgt.Path)
	if err != nil {
		t.Fatal(err)
	}
	// The command must be embedded as a JSON-encoded JS string literal so
	// backticks and ${...} in the path cannot terminate or interpolate the
	// surrounding JS, and must be injected raw into the bun shell.
	want, _ := json.Marshal(hookCmd)
	if !strings.Contains(string(raw), "const command = "+string(want)) {
		t.Errorf("command not JSON-encoded into the plugin:\n%s", raw)
	}
	if !strings.Contains(string(raw), "$`${{ raw: command }}`") {
		t.Errorf("command not injected raw into the bun shell:\n%s", raw)
	}
}

func TestReinstallOpenCodeSameCommandIsNoOp(t *testing.T) {
	tgt := openCodeTarget(t)
	installOpenCode(tgt, "clickup-axi context")
	if r := installOpenCode(tgt, "clickup-axi context"); r.Action != AlreadyInstalled {
		t.Errorf("action = %v, want AlreadyInstalled", r.Action)
	}
}

func TestReinstallOpenCodeNewCommandRepairs(t *testing.T) {
	tgt := openCodeTarget(t)
	installOpenCode(tgt, `"/old/clickup-axi" context`)
	if r := installOpenCode(tgt, "clickup-axi context"); r.Action != Repaired {
		t.Errorf("action = %v, want Repaired", r.Action)
	}
	raw, _ := os.ReadFile(tgt.Path)
	if strings.Contains(string(raw), "/old/") {
		t.Errorf("repair left the old path behind:\n%s", raw)
	}
}

func TestOpenCodeNeverTouchesUnmanagedFile(t *testing.T) {
	tgt := openCodeTarget(t)
	if err := os.MkdirAll(filepath.Dir(tgt.Path), 0o755); err != nil {
		t.Fatal(err)
	}
	user := "export const MyPlugin = async () => ({})\n"
	if err := os.WriteFile(tgt.Path, []byte(user), 0o644); err != nil {
		t.Fatal(err)
	}
	if r := installOpenCode(tgt, "clickup-axi context"); r.Action != Failed {
		t.Errorf("install over user file: action = %v, want Failed", r.Action)
	}
	if r := removeOpenCode(tgt); r.Action != Failed {
		t.Errorf("remove of user file: action = %v, want Failed", r.Action)
	}
	raw, _ := os.ReadFile(tgt.Path)
	if string(raw) != user {
		t.Errorf("user file was modified")
	}
}

func TestRemoveOpenCode(t *testing.T) {
	tgt := openCodeTarget(t)
	if r := removeOpenCode(tgt); r.Action != NotInstalled {
		t.Errorf("missing file: action = %v, want NotInstalled", r.Action)
	}
	installOpenCode(tgt, "clickup-axi context")
	if r := removeOpenCode(tgt); r.Action != Removed {
		t.Errorf("action = %v, want Removed", r.Action)
	}
	if _, err := os.Lstat(tgt.Path); !os.IsNotExist(err) {
		t.Errorf("plugin file still exists")
	}
}
